name: Deploy to GitHub Pages

on:
  push:
    branches: [ gh-pages ]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 9.1.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.19.0
          cache: pnpm

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Install NPM dependencies
        run: pnpm install

      - name: prebuild
        run: pnpm docs:prebuild

      - name: Build
        run:
          pnpm docs:build
          touch docs/.vitepress/dist/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

        with:
          path: docs/.vitepress/dist

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
